name: Build and package MachineTEST2 as DMG

on:
  push:
    branches: [main]

jobs:
  build-dmg:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find app.py path
        id: find_app
        run: |
          APP_PATH=$(find . -name app.py | head -n 1)
          echo "app_path=$APP_PATH" >> $GITHUB_OUTPUT

      - name: Clean previous builds
        run: rm -rf build dist *.egg-info

      - name: Setup Python 3.11 virtual environment
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel py2app

      - name: Create setup.py dynamically
        run: |
          echo "from setuptools import setup" > setup.py
          echo "APP = ['$APP_PATH']" >> setup.py
          echo "OPTIONS = {'argv_emulation': True}" >> setup.py
          echo "setup(app=APP, options={'py2app': OPTIONS}, setup_requires=['py2app'])" >> setup.py
        env:
          APP_PATH: ${{ steps.find_app.outputs.app_path }}

      - name: Build .app with py2app
        run: |
          source venv/bin/activate
          python setup.py py2app

      - name: Debug dist folder contents
        run: ls -l dist

      - name: Create DMG with hdiutil
        run: |
          mkdir -p dist-dmg
          if [ ! -d dist/app.app ]; then
            echo "Error: dist/app.app not found!"
            exit 1
          fi

          mkdir -p temp_dmg
          cp -R dist/app.app temp_dmg/

          hdiutil create -volname "MachineTEST2" -srcfolder temp_dmg -ov -format UDZO dist-dmg/MachineTEST2.dmg

          rm -rf temp_dmg

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: MachineTEST2.dmg
          path: dist-dmg/MachineTEST2.dmg

