name: Test app.deb

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Find app.deb
        id: find_deb
        run: |
          DEB_PATH=$(find . -type f -name "app.deb" | head -n 1)
          if [ -z "$DEB_PATH" ]; then
            echo "❌ Aucun app.deb trouvé"
            exit 1
          fi
          echo "✅ app.deb trouvé : $DEB_PATH"
          echo "deb_path=$DEB_PATH" >> $GITHUB_OUTPUT

      - name: Install dependencies for testing
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Install app.deb
        run: |
          sudo dpkg -i "${{ steps.find_deb.outputs.deb_path }}" || sudo apt-get install -f -y

      - name: Test app launch (headless)
        run: |
          echo "🧪 Test lancement de l'appli installée..."
          # Remplace 'app' par le nom exact de ton exécutable installé (ex: 'monapp')
          timeout 5 xvfb-run -a /usr/local/bin/app &> output.log || true

          if grep -q "Traceback" output.log; then
            echo "❌ L'application a planté !"
            cat output.log
            exit 1
          else
            echo "✅ Lancement réussi (aucune exception détectée)"
          fi
