name: Build Linux Executable

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          # Installe les dépendances du projet si requirements.txt existe
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          
          # Installe PyQt5 et PyQtWebEngine explicitement
          pip install PyQt5 PyQtWebEngine pyinstaller

      - name: Find app.py
        id: find_app
        run: |
          FILE_PATH=$(find . -type f -name "app.py" | head -n 1)
          if [ -z "$FILE_PATH" ]; then
            echo "❌ app.py introuvable"
            exit 1
          fi
          echo "✅ Fichier trouvé : $FILE_PATH"
          echo "file_path=$FILE_PATH" >> $GITHUB_OUTPUT

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile "${{ steps.find_app.outputs.file_path }}"

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: dist/*
